version: '3.3'

services:
  aether-pub-server:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '8080:8080'
    networks:
      - rocket

networks:
  rocket:
    external: true
